// <auto-generated />
namespace Psydpt.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Added_PK_Contraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_PK_Contraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201501121223131_Added_PK_Contraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
